import {settings,put} from './storage.js';
import {shuffle,esc,uid,copy,toast} from './utils.js';
function conflicts(groups,pairs){return pairs.reduce((n,[a,b])=>n+groups.filter(g=>g.includes(a)&&g.includes(b)).length,0)}
function missingPreferred(groups,pairs){return pairs.reduce((n,[a,b])=>n+(groups.some(g=>g.includes(a)&&g.includes(b))?0:1),0)}
function makeBySize(names,size,avoid,prefer){let best=[],score=1e9;for(let t=0;t<300;t++){const a=shuffle(names),g=[];for(let i=0;i<a.length;i+=size)g.push(a.slice(i,i+size));const s=conflicts(g,avoid)*10+missingPreferred(g,prefer);if(s<score){best=g;score=s;if(!s)break}}return best}
function makeByCount(names,count,avoid,prefer){let best=[],score=1e9;for(let t=0;t<300;t++){const a=shuffle(names),g=Array.from({length:Math.min(count,names.length)},()=>[]);a.forEach((n,i)=>g[i%g.length].push(n));const s=conflicts(g,avoid)*10+missingPreferred(g,prefer);if(s<score){best=g;score=s;if(!s)break}}return best}
export async function renderGroups(root){let groups=[];let dragName=null;const names=settings.get('classList',[]);root.innerHTML=`<div class="topbar"><div><div class="title">Groepjesmaker</div><div class="subtitle">Aantal leerlingen: ${names.length}</div></div></div>${!names.length?'<div class="card">Voeg eerst je klassenlijst toe bij Instellingen.</div>':''}<div class="card"><div class="field"><label>Groepsindeling</label><select id="groupMode" class="select"><option value="2">Tweetallen</option><option value="3">Groepjes van 3</option><option value="4">Groepjes van 4</option><option value="5">Groepjes van 5</option><option value="size">Zelf groepsgrootte kiezen</option><option value="count">Zelf aantal groepen kiezen</option></select></div><div class="field hidden" id="customWrap"><label id="customLabel">Groepsgrootte</label><input id="customValue" type="number" min="2" max="12" value="4" class="input"></div><button class="btn" id="makeGroups" ${!names.length?'disabled':''}>Maak groepjes</button></div><div class="card"><div class="section-title">Combinaties</div><div class="muted">Optioneel: geef aan wie juist niet of wel samen moet.</div><div class="pair-grid"><select id="p1" class="select">${names.map(n=>`<option>${esc(n)}</option>`).join('')}</select><select id="p2" class="select">${names.map(n=>`<option>${esc(n)}</option>`).join('')}</select></div><div class="row" style="margin-top:9px"><button id="addAvoid" class="btn secondary small">Niet samen</button><button id="addPrefer" class="btn secondary small">Juist samen</button></div><div id="pairList" class="list" style="margin-top:10px"></div></div><div id="groups" class="groups"></div><div id="groupActions" class="row hidden" style="margin-top:12px"><button class="btn secondary" id="reshuffle">Opnieuw verdelen</button><button class="btn secondary" id="copyGroups">Kopiëren</button><button class="btn" id="saveGroups">Opslaan</button><button class="btn secondary" id="shareGroups">Delen</button></div>`;
const sel=root.querySelector('#groupMode'),wrap=root.querySelector('#customWrap'),label=root.querySelector('#customLabel'),out=root.querySelector('#groups'),actions=root.querySelector('#groupActions');sel.onchange=()=>{wrap.classList.toggle('hidden',!['size','count'].includes(sel.value));label.textContent=sel.value==='count'?'Aantal groepen':'Groepsgrootte'};
function pairState(){return {avoid:settings.get('avoidPairs',[]),prefer:settings.get('preferPairs',[])}}
function drawPairs(){const {avoid,prefer}=pairState(),el=root.querySelector('#pairList');const rows=[...avoid.map((p,i)=>({type:'avoid',i,p})),...prefer.map((p,i)=>({type:'prefer',i,p}))];el.innerHTML=rows.length?rows.map(r=>`<div class="item row"><span class="grow"><strong>${r.type==='avoid'?'Niet samen':'Juist samen'}:</strong> ${esc(r.p[0])} + ${esc(r.p[1])}</span><button class="icon-btn danger-text" data-pair="${r.type}:${r.i}">×</button></div>`).join(''):'<span class="muted">Geen combinaties ingesteld.</span>';el.querySelectorAll('[data-pair]').forEach(b=>b.onclick=()=>{const [type,ix]=b.dataset.pair.split(':');const key=type==='avoid'?'avoidPairs':'preferPairs',arr=settings.get(key,[]);arr.splice(+ix,1);settings.set(key,arr);drawPairs()})}
function addPair(key){const a=root.querySelector('#p1').value,b=root.querySelector('#p2').value;if(!a||!b||a===b)return toast('Kies twee verschillende leerlingen.');const arr=settings.get(key,[]);if(!arr.some(p=>p.includes(a)&&p.includes(b)))arr.push([a,b]);settings.set(key,arr);drawPairs()}
root.querySelector('#addAvoid').onclick=()=>addPair('avoidPairs');root.querySelector('#addPrefer').onclick=()=>addPair('preferPairs');
function draw(){out.innerHTML=groups.map((g,i)=>`<div class="card group-card" data-group="${i}"><strong>Groep ${i+1}</strong>${g.map(n=>`<div class="student" draggable="true" data-name="${esc(n)}">${esc(n)}</div>`).join('')}</div>`).join('');actions.classList.toggle('hidden',!groups.length);out.querySelectorAll('.student').forEach(el=>{el.ondragstart=()=>dragName=el.dataset.name;el.onclick=()=>dragName=el.dataset.name});out.querySelectorAll('[data-group]').forEach(card=>{card.ondragover=e=>e.preventDefault();card.ondrop=e=>{e.preventDefault();move(dragName,+card.dataset.group)};card.onclick=e=>{if(e.target===card&&dragName)move(dragName,+card.dataset.group)}})}
function move(name,to){if(!name)return;let from=-1;groups.forEach((g,i)=>{const ix=g.indexOf(name);if(ix>=0){from=i;g.splice(ix,1)}});if(from>=0)groups[to].push(name);dragName=null;draw()}
function generate(){const {avoid,prefer}=pairState();if(sel.value==='count')groups=makeByCount(names,Math.max(2,+root.querySelector('#customValue').value||4),avoid,prefer);else groups=makeBySize(names,sel.value==='size'?Math.max(2,+root.querySelector('#customValue').value||4):+sel.value,avoid,prefer);draw()}
const text=()=>groups.map((g,i)=>`Groep ${i+1}: ${g.join(', ')}`).join('\n');root.querySelector('#makeGroups').onclick=generate;root.querySelector('#reshuffle').onclick=generate;root.querySelector('#copyGroups').onclick=()=>copy(text());root.querySelector('#shareGroups').onclick=async()=>{if(navigator.share)try{await navigator.share({title:'Groepjes',text:text()})}catch{}else copy(text())};root.querySelector('#saveGroups').onclick=async()=>{await put('savedGroups',{id:uid(),createdAt:new Date().toISOString(),groups});toast('Groepjes opgeslagen')};drawPairs()}
