import {getAll,put,del,settings} from './storage.js';
import {uid,esc,toast} from './utils.js';
let activeAudio=[];
export async function renderSoundboards(root){let selected=null;root.innerHTML=`<div class="topbar"><div><div class="title">Soundboards</div><div class="subtitle">Eigen geluiden voor in de klas.</div></div></div><div id="boardsView"><div class="card"><div class="row"><input id="newBoardName" class="input grow" placeholder="Naam soundboard"><button id="newBoard" class="btn">Nieuw soundboard</button></div></div><div id="boards" class="grid"></div></div><div id="boardDetail" class="hidden"></div>`;
const boardsEl=root.querySelector('#boards'),detail=root.querySelector('#boardDetail'),overview=root.querySelector('#boardsView');
async function drawBoards(){const boards=await getAll('soundboards');boardsEl.innerHTML=boards.length?boards.map(b=>`<div class="tile" data-board="${b.id}"><div class="icon">🔊</div><strong>${esc(b.name)}</strong><span class="muted">Open soundboard</span></div>`).join(''):'<div class="muted">Nog geen soundboards.</div>';boardsEl.querySelectorAll('[data-board]').forEach(t=>t.onclick=()=>openBoard(t.dataset.board))}
root.querySelector('#newBoard').onclick=async()=>{const n=root.querySelector('#newBoardName').value.trim();if(!n)return toast('Geef het soundboard een naam.');await put('soundboards',{id:uid(),name:n,createdAt:new Date().toISOString()});root.querySelector('#newBoardName').value='';drawBoards()};
async function openBoard(id){selected=(await getAll('soundboards')).find(x=>x.id===id);if(!selected)return;overview.classList.add('hidden');detail.classList.remove('hidden');detail.innerHTML=`<div class="topbar"><button id="backBoards" class="btn secondary small">← Terug</button><div style="text-align:right"><div class="section-title" style="margin:0">${esc(selected.name)}</div></div></div><div class="card"><div class="field"><label>Geluid toevoegen</label><input id="soundFile" type="file" accept="audio/*" class="input"></div><div class="row"><input id="soundName" class="input grow" placeholder="Naam van geluid"><button id="addSound" class="btn">Toevoegen</button></div></div><div id="sounds" class="sound-grid"></div><div class="row" style="margin-top:14px"><button id="renameBoard" class="btn secondary small">Hernoemen</button><button id="deleteBoard" class="btn danger small">Soundboard verwijderen</button></div>`;detail.querySelector('#backBoards').onclick=()=>{stopAll();detail.classList.add('hidden');overview.classList.remove('hidden');drawBoards()};detail.querySelector('#addSound').onclick=addSound;detail.querySelector('#renameBoard').onclick=async()=>{const n=prompt('Nieuwe naam:',selected.name);if(n?.trim()){selected.name=n.trim();await put('soundboards',selected);openBoard(selected.id)}};detail.querySelector('#deleteBoard').onclick=async()=>{if(!confirm('Dit soundboard en alle geluiden verwijderen?'))return;for(const s of (await getAll('sounds')).filter(x=>x.boardId===selected.id))await del('sounds',s.id);await del('soundboards',selected.id);detail.querySelector('#backBoards').click()};drawSounds()}
async function addSound(){const file=detail.querySelector('#soundFile').files[0],name=detail.querySelector('#soundName').value.trim()||file?.name;if(!file)return toast('Kies eerst een audiobestand.');await put('sounds',{id:uid(),boardId:selected.id,name,blob:file,createdAt:new Date().toISOString()});detail.querySelector('#soundFile').value='';detail.querySelector('#soundName').value='';drawSounds()}
async function drawSounds(){const sounds=(await getAll('sounds')).filter(x=>x.boardId===selected.id),el=detail.querySelector('#sounds');el.innerHTML=sounds.length?sounds.map(s=>`<div class="sound-tile"><button class="sound-btn" data-play="${s.id}">▶<br>${esc(s.name)}</button><div class="row"><button class="btn secondary small" data-rename="${s.id}">Naam</button><button class="btn danger small" data-del="${s.id}">Wis</button></div></div>`).join(''):'<div class="muted">Nog geen geluiden toegevoegd.</div>';el.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>play(sounds.find(s=>s.id===b.dataset.play),b));el.querySelectorAll('[data-rename]').forEach(b=>b.onclick=async()=>{const s=sounds.find(x=>x.id===b.dataset.rename);const n=prompt('Nieuwe naam:',s.name);if(n?.trim()){s.name=n.trim();await put('sounds',s);drawSounds()}});el.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{await del('sounds',b.dataset.del);drawSounds()})}
function stopAll(){activeAudio.forEach(a=>{try{a.pause();URL.revokeObjectURL(a.src)}catch{}});activeAudio=[]}
function play(s,btn){if(!settings.get('multiAudio',false))stopAll();const url=URL.createObjectURL(s.blob),a=new Audio(url);activeAudio.push(a);btn.classList.add('playing');a.onended=()=>{btn.classList.remove('playing');URL.revokeObjectURL(url);activeAudio=activeAudio.filter(x=>x!==a)};a.play().catch(()=>toast('Dit audiobestand kon niet worden afgespeeld.'))}drawBoards()}
